###LOGIN
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "Faelala@ejemplo.com",
    "password": "flan"
}
###IMAGEN A PROCESAR

POST http://localhost:3001/picture
Content-Type: application/json

{
     "id": "6625ab80659d7afd5fc5c13a",
    "link":"https://res.cloudinary.com/vikingr-saga/image/upload/v1688347761/samples/sheep.jpg"
}